# Generated by Django 5.1.3 on 2024-11-28 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True, null=True)),
                ('photo', models.TextField(blank=True, null=True)),
                ('viewse', models.TextField(default=0)),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('published', models.BooleanField(default=True)),
            ],
        ),
    ]
